version: '3.9'

services:
  backend:
    build: ./book-shop
    env_file: ./book-shop/.env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - bookshop_net
      
  db:
    image: postgres:15
    env_file: ./book-shop/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookshop_net

volumes:
  postgres_data:
  static_volume:

networks:
  bookshop_net:
    driver: bridge